name: release

on:
  release:
    types: [created]

# Copied from https://crates.io/docs/trusted-publishing
jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: release  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Setup
      run: |
        sudo apt -y install clang-20
        rustup target add riscv64imac-unknown-none-elf
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
